# Generated by Django 5.0.4 on 2024-05-04 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.FloatField()),
                ("is_game_terminated", models.BooleanField()),
                ("white_value", models.FloatField()),
                ("black_value", models.FloatField()),
                ("fen", models.CharField(max_length=255)),
                ("num_visits", models.IntegerField(default=1)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="game.gamestate",
                    ),
                ),
            ],
        ),
    ]
