# Generated by Django 5.0.4 on 2024-05-06 14:34

import django.db.models.deletion
import pieces.utilites
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("board_hash", models.BinaryField()),
                ("is_game_terminated", models.BooleanField()),
                ("white_value", models.FloatField()),
                ("black_value", models.FloatField()),
                ("fen", models.CharField(max_length=255)),
                (
                    "player_turn",
                    models.IntegerField(choices=pieces.utilites.PieceColor.choices),
                ),
                ("current_turn", models.IntegerField()),
                ("num_visits", models.IntegerField(default=1)),
                ("expandable_moves", models.JSONField()),
                ("explored_moves", models.JSONField(default=list)),
                ("move_taken", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="game.gamestate",
                    ),
                ),
            ],
        ),
    ]
